### ISSUE TITLE
How to schedule a email for particular date-time?

### ISSUE THREAD

**Issue by turivishal** [sendinblue/APIv3-nodejs-library#102]
How to schedule a email for particular date-time, for example when i schedule it for 2nd Jan at 02PM, that email should send at that time, i did not found in github readme or documentation, 

and also if its possible then it is possible to cancel scheduled for that particular time?

**Comment by shubhamUpadhyayInBlue** [comment]
Hey @turivishal 
We have this option to schedule an email campaign [here](https://developers.sendinblue.com/reference#createemailcampaign-1). You can use the `scheduledAt` field to define the date and time at which you would like to send the email campaign. 

Also, if you want to cancel the scheduled email then use this [API](https://developers.sendinblue.com/reference#updatecampaignstatus) and update the `status` to be `suspended` for that particular campaign.

Hope it helps!
