### ISSUE TITLE
Empty params throw an error, even though docs list them as optional

### ISSUE THREAD

**Issue by kybishop** [sendinblue/APIv3-nodejs-library#103]
We have a template that doesn't use any params. When attempting to send an email with no params, which the docs list as optional [here](https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/SendSmtpEmail.md), it fails with `"status":400,"text":"{\"code\":\"missing_parameter\",\"message\":\"params is blank\"}`.

Adding a bogus param fixes the issue, so either the docs should be updated, or params actually made optional.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @kybishop 

The reason for this error is that you are passing an empty `params` object in the payload i.e. `params: {}`
Here is an example in the attachment where I sent a template without using the params object in the request body.

![Screenshot 2021-06-09 at 9 49 52 PM](https://user-images.githubusercontent.com/52399364/121393435-f68d3680-c96d-11eb-9514-5295d91d426c.png)

Happy to help!
Shubham
