### ISSUE TITLE
Import a List of contacts with the API

### ISSUE THREAD

**Issue by matamicen** [sendinblue/APIv3-nodejs-library#107]
Hi,
We are using :

`var createContact = new SibApiV3Sdk.CreateContact();`

but we need to import a list of contacts with one API CALL, is this possible?

Thanks

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @matamicen 

Yes, it is possible to import the contacts using the import route, [https://developers.sendinblue.com/reference/contacts-7#importcontacts-1](documentation). 
- The endpoint is `https://api.sendinblue.com/v3/contacts/import`
- You can either pass the contacts using `fileUrl` or `fileBody`

Thanks!
