### ISSUE TITLE
Enhancement request - option to disable URL replacement

### ISSUE THREAD

**Issue by ericdesa** [sendinblue/APIv3-nodejs-library#115]
When we send transactional email, URL are replaced to be tracked by sendinblue

It's explained here : 
https://help.sendinblue.com/hc/en-us/articles/209421325-Why-is-the-URL-of-my-links-different-from-what-I-have-chosen-

However, I would like to disable this feature because :  
- some of my clients block these emails
- i already experienced errors because the domaine was temporarily not reachable

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @ericdesa 

Apologies for replying so late. As you correctly pointed to our help article. It is not possible to remove the link tracking. However, I will convey your request and share as soon as I have an update on it.

Happy to help!
Shubham

**Comment by yogo1212** [comment]
We are considering switching to sendinblue and are also facing this issue.
We had no problems with server availability, though.
One test mail for a MFA token was classified as "potential phishing" for a business client who has multiple logins under their domain.

The plain-text transactional email is converted to HTML automatically and tracking is added.
Sending the same email from our old provider (with the tracking added by sendinblue) also results in the phishing warning.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @yogo1212 
It looks like your case needs a closer look so I would request you raise a support ticket. Steps for that:
- Login to your Sendinblue account
- Visit this [link](https://app.sendinblue.com/account/zendesk-support). You will then be redirected to the support ticket creation page.

**Comment by ericdesa** [comment]
I understand that it's not a prior request, but just to let you know that we are going to leave sendinblue because of that.
It's not often, but when our clients can't follow our links when your service is down (like right now) it's a major issue (in addition to the security issue)
You can close this request if you want.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @ericdesa 
It is sad that we could not satisfy your needs. If you would like us to cater to your problem in a more personalized way, please raise a support ticket. I am closing this request here.
Thanks!

**Comment by alterphp** [comment]
Hi,

It's so bad you do not consider this request. We can not use mobile application dynamic links with Sendinblue because Android (in some versions) and iOS (in all versions) do not accept redirections on dynamic links.

**Comment by alterphp** [comment]
Does anyone know another email provider that allows to disable tracking (url rewriting) on specific links ?

**Comment by that-one-tom** [comment]
> Does anyone know another email provider that allows to disable tracking (url rewriting) on specific links ?

Yes, Sendgrid allows this for example on a global level ([docs](https://docs.sendgrid.com/ui/analytics-and-reporting/click-tracking-html-best-practices)) and also for each link individually through an attribute ([docs](https://docs.sendgrid.com/ui/analytics-and-reporting/click-tracking-html-best-practices)). 

I am currently testing out Sendinblue after lots of positive reviews, but not being able to prevent tracking (in addition with the TLS encryption only working for some email providers on the recipient side) seems like a major shortcoming compared to other providers for certain transactional messages.

**Comment by ChuckJonas** [comment]
the link redirect breaks our URL encoding.  I think the only reason people use this service is because they have a decent free tier.  Otherwise it's a horrible dev experience..

**Comment by NateFerrero** [comment]
This is currently affecting me and I might have to switch off of Sendinblue for this reason. Links are not preserving the hash component properly.

**Comment by wolak88** [comment]
That is really unfortunate, due to this being unresolved and support not helping as well we have to leave Sendinblue as well.

**Comment by emeren** [comment]
> That is really unfortunate, due to this being unresolved and support not helping as well we have to leave Sendinblue as well.

same...

**Comment by CamParry** [comment]
This is also causing issues for our clients, it would be great if there was a way to disable URL replacement for emails. Currently when a link is clicked it just goes to a white page and takes anywhere between 5-20 seconds before the page redirects, and users have interpreted this as being broken.

**Comment by alisommartins** [comment]
i'm facing HTTP 404 for this links, i'm just looking for some option to disabled click tracking, but nothing was found
![image](https://user-images.githubusercontent.com/7538868/223222997-614d3de7-20e6-4fd2-a237-da433222301e.png)

**Comment by Yeronimo** [comment]
Is there any news on this? For example we are using a Table of Contents in our newsletter (transactional/smtp emails), with links to anchors, to the links are something this: #anchor1 

Send in blue makes it into their tracking link, which in turn gets picked up by email protect like so: https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fr.sendermail%2ftr%2fcl%2fNscx8J8HHIshbuY0NrHkDjjjFwmN1231313SoK0pVKQc8VZ3bfIHvPrg4-keiSk7v1QhICsz0mTcLK_KMCM-jQ4WNOBaWirGhuLl_y3jNcYeiGJ83ccmDh1Xqso8UeUpEwG_13123123Aa62-dmStx6cB2eTS1H3Zqg2kxWPd829Xd5jIDJ0Q6f1h-qPhIZf5yxq0tuE6&c=E,1,9wr_7WVzTuNLl6ULCXo0QRpaCdDxjC79ouTD-TIy60_hodEb1upXCbgIuJAd4QVojJPY8OzAfKxtbJMe6GII8iV52xERex2yXiwwEVFiWH5H_sEatqfnG8CLHA,,&typo=1

So now these anchors of course won't work. Is there a way around this?

**Comment by erimfranci** [comment]
I got link tracking turned off by contacting the Sendinblue customer support. They ask you whether you want to disable link tracking for campaigns or transactional emails or both. Hope it helps!

**Comment by Yeronimo** [comment]
> I got link tracking turned off by contacting the Sendinblue customer support. They ask you whether you want to disable link tracking for campaigns or transactional emails or both. Hope it helps!

I need to be able to disable certain links in an e-mail, so not a solution for me. What did work was changing the anchor from:

`<a href='#anchor1'>Go to anchor 1</a>`

To this, so adding spaces around the = :

`<a href = '#anchor1'>Go to anchor 1</a>`

**Comment by IanBod** [comment]
We will need tracking turned off as we are creating a specialised CRM and we will be generating our own tracking solution on a per-client basis.  I shall contact Send In Blue and see what they can do.  Thanks to those who have reported back on this.

**Comment by mhaarmann** [comment]
This article says, it is not possible to turn off the tracking (anymore): https://help.sendinblue.com/hc/en-us/articles/209421325?input_string=turn+of+link+tracking
So there is no way around it?
The workaround with adding spaces around the equal signs does not work for me.

**Comment by Hemligg** [comment]
You should really make sure to implement a way to turn off the redirection links. Especially since it obviously can happen that the redirection links will stop working as they just have. And now we can only pray it won't take long to fix the issue. But so far more than an hour has past since they stopped working. :/
![FireShot Capture 476 - Brevo System Status - status brevo com](https://user-images.githubusercontent.com/67462206/236824351-5c6a0e77-e4ec-4376-bc68-116e0fb47ca5.png)

**Comment by haywirez** [comment]
Not having the option to disable replacement is crazy—how do you expect people to use your service for transactional password reset emails?

**Comment by matteocontrini** [comment]
Confirming that you can contact support and request to disable open and/or link tracking on transactional and/or marketing emails.

No clue why this isn't simply an option like with every other email service.

**Comment by christophostertag** [comment]
Is there already a solution for this problem? Some of our subscribers are getting messages that the url is fraud.

<img width="289" alt="Screenshot 2023-10-18 at 17 39 28" src="https://github.com/sendinblue/APIv3-nodejs-library/assets/37454333/f4c3f00a-0286-46a8-93c1-644530473c84">

I would prefer to just set utm parameters instead.

**Comment by m14e** [comment]
I contacted Brevo and they were not able to turn off link replacement. 

I'm looking for a new SMTP provider now - preferably one with servers in the EU or Canada; suggestions are welcome.

**Comment by matteocontrini** [comment]
@m14e what did you ask exactly? They managed to do that without insisting when I asked in July.

**Comment by sergomet** [comment]
any updates? having the same problem.

**Comment by MrJibus** [comment]
Same problem here. I contacted Brevo, and they denied my request.

I tried to insist, but this was their answer :

_Unfortunately, the decision from our Compliance team is final and they won't be turning off the link tracking._

**Comment by BenStirrup** [comment]
Any update regarding the possibility of deactivating link tracking ?

**Comment by naourass** [comment]
I'm running into this issue too. I have tokens in the links. Switching to another provider since I can't use Brevo for transactional emails.

**Comment by kamzil** [comment]
This is just hilarious. Issue opened 4+ years ago and it's still a problem. No one cares.

How so many people are recommending this service puzzles me. Maybe they just want to send low-cost spam and don't care about having actually functional websites.

Like others in this thread, will move to another provider and recommend anyone I know against using this service.

Thx bye.

**Comment by boudhayan-dev** [comment]
Using templates have atleast fixed the broken urls for now. but there is no way around rewriting of the urls.

**Comment by Psycarlo** [comment]
I was trying Brevo and everything was going right, and then, I just jumped into this problem.
Without the option to disable URL replacement with Brevo's tracking URL, I can't send users Magic Links to login, because Brevo will consume this link when the user clicks on the button and then the link will expire.

Sad to see that this issue has 4+ years and the Brevo Team does not care.

**Comment by kerwitz** [comment]
I realise this repo is old, but since Google lead me here..

This really is a mess. It's obvious this is not intended to be turned off for pure product marketing reasons, as you probably intend to provide more service than acting as another simple mail server. By all means, do that. Your product, your agenda. But then communicate more openly about it, will you? The docs do not mention this, neither does any page during sign up and setup. Why on earth would I want to track clicks in password reset or confirmation emails. This is nuts. I, too, am switching.

**Comment by gregorko** [comment]
Have you tried sending a support request? I asked Brevo to remove link tracking on campaign and transactional mails and did not take a day until it was disabled.

**Comment by kerwitz** [comment]
No, and really why would I. This shouldn't be enabled by default to begin with, nor should it be a manual process for me to disable it. I don't intend to do business with a company like this. Hence I'll move on. As I said: their product, their decisions and I respect that. Bad decisions in this case as far as I am concerned. Still others may want it exactly this way, don't care for it at all, or are okay with reaching out to them like you did. That's alright with me.
