### ISSUE TITLE
We should not url encode params

### ISSUE THREAD

**Issue by hadrien-f** [sendinblue/APIv3-nodejs-library#129]
Hello,

I noticed the documentation mentions we have to url encode params used in url path.
For example to unblock a transactional contact :
https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/TransactionalEmailsApi.md?plain=1#L1194

However in apiClient.js you already url encode each params in the url :
https://github.com/sendinblue/APIv3-nodejs-library/blob/ecf167b9b9da2802f9bae858ecc8fb723cc80d23/src/ApiClient.js#L143

So we should not do it as the documentation mentions.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @hadrien-f 

You only have to encode the parameters which are being passed:
- Either as a path parameter. Eg: `/contacts/<your-email-url-encoded>`
- Or as a query parameter. Eg: `/contacts?email=<your-email-url-encoded>`

But, in this endpoint to send a transacitonal email you are passing all the values in the body of the request. There is no need to urlEncode it.

Happy to help!
Shubham
