### ISSUE TITLE
We shouldn't have to tweak Webpack to get the lib to work

### ISSUE THREAD

**Issue by louisremi** [sendinblue/APIv3-nodejs-library#13]
Hi guys,
That new version of your SDK looks neat! I've got one problem though: why do I have to tweak my Webpack config to get it to work?
The name of the lib is _APIv3-**nodejs**-library_, so I don't really understand why you wouldn't just use `require` in your code, instead of the (outdated) headers you've added to each files.

I was lucky enough not to get into troubles when I added your workaround to my Webpack config, but I'm pretty not everyone out there will be as lucky.

Please let me know if you had other constraints when writing this lib, and if you'd be willing to find a solution to this problem :-)

**Comment by luiscarbonell** [comment]
Creating a modern API - even completely overhauling this one - should only be a a "couple day" project with libraries like `restify`. Is there any technical reason why that is not currently being done?

@louisremi As you pointed modifying a Webpack could create some conflicts for a lot of larger projects. 

@ekta-slit Would you be open to using a library like `restify` for the sake of simplicity and portability?

**Comment by luiscarbonell** [comment]
Hey guys, 

I put together a simple Node.js API Client (https://github.com/luiscarbonell/sendinblue-v3-node-client) without any of the Webpack complications. 

@ekta-slit Check it out! If you like the changes, let's go ahead and port them over to this repo?

So far, I have some rudimentary tests and almost identical documentation for ease of use.

Best.

**Comment by ekta-slit** [comment]
Hi @louisremi @luiscarbonell 

Thanks for reporting the issue and thanks for sharing the API Client (looks neat), respectively.

FYI this API client is an auto-generated code via `swagger-codegen`. I found some solutions to the similar problem. Please refer below links-
- https://stackoverflow.com/questions/44356241/how-to-bundle-swagger-generated-code-with-webpack
- For webpack https://github.com/swagger-api/swagger-codegen/issues/3336#issuecomment-232126946
- For webpack 2 https://github.com/swagger-api/swagger-codegen/issues/3336#issuecomment-283494974

@luiscarbonell For now we will be using this auto-generated Node.js API Client ( as workaround for this is available ) and your repo definitely can help other clients if they don't want to play with their webpack file :)

Thanks
