### ISSUE TITLE
Unable to include the module on Ubuntu

### ISSUE THREAD

**Issue by jjalan** [sendinblue/APIv3-nodejs-library#23]
At app start on Ubuntu in a node application, I see following error:

<img width="991" alt="screen shot 2018-02-01 at 11 18 51 am" src="https://user-images.githubusercontent.com/328858/35663235-3045eecc-0742-11e8-8cf0-93dc7b7a15db.png">

The model file is named RequestSMSRecipientExport (note SMS all caps). However it is included as RequestSmsRecipientExport.

**Comment by ekta-slit** [comment]
Hi @jjalan 

Issue has been fixed, please check.

Thanks

**Comment by atorgfr** [comment]
@ekta-slit Yes but the package on npm haven't been updated
