### ISSUE TITLE
Send Template

### ISSUE THREAD

**Issue by Dallas62** [sendinblue/APIv3-nodejs-library#25]
Hi!

I can not send mail with SendTemplate:

```
    const apiInstance = new SibApiV3Sdk.SMTPApi();

    apiInstance.sendTemplate(123, {
            emailTo: 'adress@domain.tld'
        })
```

Result:

```
{"code":"invalid_parameter","message":"valid emailTo is required"}
```

Of course, I provide a valid mail when I run the process.

**Comment by ekta-slit** [comment]
Hi @Dallas62 

`emailTo` expects an array of email addresses & not string.
So code should be like:

```
const apiInstance = new SibApiV3Sdk.SMTPApi();

    apiInstance.sendTemplate(123, {
            emailTo: ['adress@domain.tld']
        })
```

Refer https://developers.sendinblue.com/v3.0/reference#sendtemplate-1

Thanks

**Comment by Dallas62** [comment]
Thanks! Will check this ASAP.

An idea: Make pre-validation of type or transformation into array might be done to avoid confusion.
