### ISSUE TITLE
Error in sdk

### ISSUE THREAD

**Issue by atorgfr** [sendinblue/APIv3-nodejs-library#32]
There is an error on the npm package

Error: Cannot find module './model/RequestSmsRecipientExport'

when we install the package on linux with npm the filename is : RequestSMSRecipientExport.js that's why there is an error.

**Comment by ekta-slit** [comment]
Hi @atorgfr 

This issue had already been fixed in https://github.com/sendinblue/APIv3-nodejs-library/releases/tag/v4.0.1
Please check and upgrade your version.

Thanks

**Comment by rocxteady** [comment]
I am getting the same error with the latest version 8.4.2. @ekta-slit
