### ISSUE TITLE
Invalid smtpBlacklistSender format error 

### ISSUE THREAD

**Issue by guillaumerxl** [sendinblue/APIv3-nodejs-library#34]
Hello, 

I'm getting an error when I try to update a contact with new attributes only.

If I don't set `smtpBlacklistSender` to `['']` manually, SB API returns:
```
// 400 BAD REQUEST
{ 
  "code":"invalid_parameter",
  "message":"Invalid smtpBlacklistSender format"
}
```

I'm using `sib-api-v3-sdk` version `4.0.1`.

**Comment by ekta-slit** [comment]
Hi @guillaumerxl 

Thanks for reporting the issue. Its had been fixed yesterday at 15:47 IST.
No changes done on `sib-api-v3-sdk` package, just the internal code.

Please check and issue is no more!

Thanks

**Comment by guillaumerxl** [comment]
Checked, it works, thanks.
