### ISSUE TITLE
Can we get typescript definitions for this

### ISSUE THREAD

**Issue by BobobUnicorn** [sendinblue/APIv3-nodejs-library#37]
It looks like swagger does support a Typescript Node client. Can we get those declaration files alongside this repo?

**Comment by isaadabbasi** [comment]
@BobobUnicorn  I just reopened this issue again,
I'd love to know if you managed to integrate it?

**Comment by ekta-slit** [comment]
Hi @BobobUnicorn 

We have planned this requirement & it will be available by the for 2nd quarter of this year.

Thanks

**Comment by JalilArfaoui** [comment]
Can't wait !

**Comment by captainjapeng** [comment]
Typescript Defs is definitely a plus!

**Comment by JClackett** [comment]
Did this not happen then?

**Comment by jonathanfallon** [comment]
Haven't tried it yet and I might extract a subset of the features for my use case.
https://github.com/sendinblue/APIv3-typescript-library

**Comment by EzzatOmar** [comment]
Any updates?

**Comment by shubhamUpadhyayInBlue** [comment]
Hey @EzzatOmar 

For typescript definitions, I recommend you try out this https://github.com/sendinblue/APIv3-typescript-library. Let me know what you find missing in it.

Thanks
Shubham
