### ISSUE TITLE
sendTemplate attributes don't appear to work

### ISSUE THREAD

**Issue by rendermusic** [sendinblue/APIv3-nodejs-library#44]
sendTransacEmail with the 'params' key works fine. However, using sendTemplate with 'attributes' leaves {{ <attr> }} tokens blank in the final email.

Tried: {{ attributes.attributeName }}, {{ params.attributeName }}, {{ attributeName }} and all are left blank.

**Comment by Yngdev31** [comment]
Did you try to this = "{ attributes.attributeName }, { params.attributeName }, { attributeName }" instead this "{{ attributes.attributeName }}, {{ params.attributeName }}, {{ attributeName }" ?

**Comment by ekta-slit** [comment]
Hi @rendermusic 

The API call [Send a transactional email](https://developers.sendinblue.com/reference#sendtransacemail) is used to send SendinBlue’s New Template Language Templates (which uses  for ex `{{ params.parameterNAME }}` for `params` replacement), please refer our [help doc](https://help.sendinblue.com/hc/en-us/articles/360000268730-Using-SendinBlue-s-New-Template-Language-to-create-email-templates-and-campaigns-NEW-) 
Wrapper link: https://developers.sendinblue.com/reference#sendtransacemail - https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/SMTPApi.md#sendTransacEmail

Now the another API call [Send a template](https://developers.sendinblue.com/reference#sendtemplate-1) which also says `This endpoint is deprecated. Prefer v3/smtp/email instead.` is used to send SendinBlue’s Old Template Language Templates (which uses for ex `%ORDER_AMOUNT%` for `attributes` replacement), again please refer our [help doc](https://help.sendinblue.com/hc/en-us/articles/209557065-Customize-transactional-email-templates-API-v2-using-the-old-template-language) 
Wrapper link: https://developers.sendinblue.com/reference#sendtemplate-1 - https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/SMTPApi.md#sendTemplate

Thanks

**Comment by SimonPasquereau** [comment]
same issue for me, here is my code:
```javascript
const defaultClient = SibApiV3Sdk.ApiClient.instance;
const apiKey = defaultClient.authentications['api-key'];
apiKey.apiKey = config.SENDINBLUE.apiKey;
const apiInstance = new SibApiV3Sdk.SMTPApi();

await apiInstance.sendTemplate(myTemplateId, {
    emailTo: [myEmail],
    params: {
      foo: 'bar',
    },
  });
```

here is my template:
Value of foo: #{{ params.foo }}#
Value of mail: #{{ contact.EMAIL }}#

here is the mail I receive:

Value of foo: ##
Value of mail: #myEmail#

I'm a bit confused, I don't know what I'm doing wrong :/
Thx for your answer

**Comment by matejicekme** [comment]
Same problem here, Up !

**Comment by gabriel-castro** [comment]
> params

was this fixed? I have same problem
