### ISSUE TITLE
Issue updating a contact

### ISSUE THREAD

**Issue by matejicekme** [sendinblue/APIv3-nodejs-library#47]
Hi there,

Got an issue updating a contact, api return an error : "Bad request". Don't know if I miss something or anything else...
Here's my code : 
```javascript
const SibApiV3Sdk = require('sib-api-v3-sdk')
const defaultClient = SibApiV3Sdk.ApiClient.instance
const apiKey = defaultClient.authentications['api-key']
apiKey.apiKey = 'xxxxxxxxx'
let toSIDInfos = {
      'NOM': userInfos.lastName,
      'PRENOM': userInfos.firstName
    }
    const apiInstance = new SibApiV3Sdk.ContactsApi()
    let updateContact = new SibApiV3Sdk.UpdateContact()
    updateContact.attributes = toSIDInfos
    updateContact.listIds = [5, 10, 11]
    if (env === 'prod') {
      apiInstance.updateContact(encodeURI(userInfos.email), updateContact).then(function () {
        console.log('SENDINBLUE: API called successfully.')
      }, function (error) {
        console.error('SENDINBLUE_ERROR :' + error)
      })
    }
```
Of course my userInfos object return right datas.

Any idea ?

Thank you

**Comment by javanotti** [comment]
+1 here. I'm having the exact same issue, even if my code looks pretty correct and the request I'm sending looks like the following:
`email =  info%40docendoacademy.eu`
```
updateContact :  {
  "attributes": {
    "field1": "a1v2",
    "field2": "a1v2",
    "field3": "a1v2",
    "field4": "a1v2",
    "field5": "a1v2",
    "field6": "81100",
    "field7": "+393999831122",
    "field8": "+393999831122"
  }

```

**Comment by matejicekme** [comment]
@ekta-slit any help with this ? This is the official SendInBlue NodeJS API for customers right ?

Thank you

**Comment by ekta-slit** [comment]
Hi @matejicekme 

Try `console.error(error.response.text);` in case of error, you will get complete error message.
Hope that helps!


Thanks

**Comment by baleo-it** [comment]
Using code of @matejicekme I get the following error when I try to update a contact:

```
{
  code: "invalid_parameter",
  message: "Contact already exist"
}
```

Of course, contact already exists because I'm trying to update!!! I dont understand my error. It seems simpler to use a regular fetch to use your API

**Comment by baleo-it** [comment]
To fix this issue, I didnt pass email address within attributes key as if email is not different, I get this error message.

**Comment by achrafha** [comment]
Did you find a solution for this problem ? I'm getting the same error message.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @ShubhamChndrvnshi 
- Your code looks fine and I also tried to update an attribute value in my account to find that it is working good ✅  

**Just a quick check for you:** Go to `https://my.sendinblue.com/lists/add-attributes` in your Sendinblue account and see if the token attribute is created.

If that doesn't help then I request you raise a support ticket from your Sendinblue account so that we can replicate it and check your database configuration.

Happy to help!

**Comment by ShubhamChndrvnshi** [comment]
> Hi @ShubhamChndrvnshi
> 
> * Your code looks fine and I also tried to update an attribute value in my account to find that it is working good white_check_mark
> 
> **Just a quick check for you:** Go to `https://my.sendinblue.com/lists/add-attributes` in your Sendinblue account and see if the token attribute is created.
> 
> If that doesn't help then I request you raise a support ticket from your Sendinblue account so that we can replicate it and check your database configuration.
> 
> Happy to help!

Hey shubham,

Thanks for the reply. I've got the solution for above query
Just need to add 
updateContact.type = "type";

After adding above the code works fine for me.
