### ISSUE TITLE
Enhancement request - support for  marketing automation tracker API

### ISSUE THREAD

**Issue by ofer-papaya** [sendinblue/APIv3-nodejs-library#52]
We are using SIB API from the server side and it would be helpful if the marketing automation tracker API would also be provided as part of the node SDK.

**Comment by zaszab** [comment]
+1

**Comment by jsjexpert** [comment]
@ofer-papaya This might be what you need:
https://www.npmjs.com/package/@wecre8websites/sendinblue-tracker
https://github.com/wecre8websites/sendinblueTracker

**Comment by ofer-papaya** [comment]
@jsjexpert thanks! it looks good and can help others that want to be able to track events or create workflows is SIB.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @jsjexpert and @ofer-papaya 
We have planned it for the coming quarter. So, closing the ticket for now.
Thanks!
