### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mishaseniv** [sendinblue/APIv3-nodejs-library#55]
I use sendTransacEmail, but i got only 

`{ Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  response: undefined }`

There is nothing in the official documentation about this problem, nor about certificates.
Why can there be a problem?

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @mishaseniv 
It seems to be a problem with your npm and not the library you are using.

A few StackOverflow traces:
- https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate

The resolution seems to be simple, please try this out https://stackoverflow.com/a/45884819.

Happy to help!
Shubham
