### ISSUE TITLE
Types missing for APIv3-nodejs-library

### ISSUE THREAD

**Issue by isaadabbasi** [sendinblue/APIv3-nodejs-library#57]
Having a completely pathetic experience first time implementing it with node.js.
Not sufficient documentation available anywhere. 
I'd be please if you add @types for entire repo rather than .md files for APIs.

**Comment by JalilArfaoui** [comment]
Same here .... :-(

**Comment by laubonghaudoi** [comment]
Seriously, the nodejs api support is so bad. I am going to use another email provider.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @isaadabbasi @JalilArfaoui and @laubonghaudoi 
I understand your concern, but this is an auto-generated wrapper from the OpenAPI spec. We have our typescript wrapper https://www.npmjs.com/package/@sendinblue/client. You can use this if you want the types.
