### ISSUE TITLE
[BUG] sendTransacSms Always return "Only alphanumeric characters are allowed"

### ISSUE THREAD

**Issue by ldewez** [sendinblue/APIv3-nodejs-library#65]
I try to send an SMS with values below : I remove all accent and I also try with +3367023xxxx as recipient number.

{
  sender: 'CHERRY C',
  recipient: '003367023xxxx',
  content: 'Vous avez gagne le concours Cherry Checkout grace a votre Don Connectez vous sur cherrycheckout pour recevoir votre prix',
  tag: 'winner' 
}

The Api return which error code and message if we have no Sms credits ?

**Comment by tikhop** [comment]
Just in case if someone bumped into the same issue, removing whitespaces from `sender` solves the problem.

**Comment by shubhamUpadhyayInBlue** [comment]
Thank you @tikhop for replying on this thread.

Hi @ldewez 
We have added validation incase of invalid sender name. Incase, you have any query or issue you can report it with our support team from your account.
Thanks!
