### ISSUE TITLE
Why so complicated

### ISSUE THREAD

**Issue by ScreamZ** [sendinblue/APIv3-nodejs-library#66]
Hello there,

just to say that you might losing a lot of user because those wrapper are too complicated.

Why can't you just make something simple as https://github.com/stripe/stripe-node did as example ?

Thanks

**Comment by picheli20** [comment]
+1

**Comment by nigelthinksprint** [comment]
+1

**Comment by Nhacsam** [comment]
I guess your answer is there : https://github.com/sendinblue/APIv3-nodejs-library/blob/master/src/api/AccountApi.js#L9
The code have been generated

**Comment by ScreamZ** [comment]
@Nhacsam Poor company… No even making a good sdk for its product :(

**Comment by shubhamUpadhyayInBlue** [comment]
Hello @ScreamZ 
The planning/discussion for wrapper is in progress. Thank you for the reference and valuable feedback.
