### ISSUE TITLE
updateContact error for email with two domain extension

### ISSUE THREAD

**Issue by Bamorem** [sendinblue/APIv3-nodejs-library#68]
Hi I use the updateContact to add a contact to a list of contact.
For an email like jhon@example.com it's working, but not for jhon@example.com.au

And yes the emails il already created, that's why i use updateContact ^^

The error is : { code: 'invalid_parameter', message: 'Invalid email address in attributes' }

Someone can help me with this ?

**Comment by SiM07** [comment]
We have an issue with this endpoint since this morning around 7:00AM and 7:59 AM (Europe/Paris)

**Comment by Bamorem** [comment]
> We have an issue with this endpoint since this morning around 7:00AM and 7:59 AM (Europe/Paris)

I have this error since  3 days now, is it related ?

**Comment by SiM07** [comment]
Not related.

**Comment by shubhamUpadhyayInBlue** [comment]
Hey @Bamorem 
I just tested with the latest version of the NodeJS wrapper and it's working good with two domain extension. You can open an L3 if you are still facing the issue.

Also, @SiM07 you can have a look at the status of APIv3 here: https://status.sendinblue.com
Thanks!
