### ISSUE TITLE
API requests pagination limits

### ISSUE THREAD

**Issue by alexkorsun** [sendinblue/APIv3-nodejs-library#77]
Hi!

Please add clear pagination limits for API requests.
https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/ContactsApi.md#getLists
https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/ContactsApi.md#getcontactsfromlist

It's really misleading. 
The limit is `int64`, what is not truth, because from what I noticed it's 500 per page maximum for [contacts](https://developers.sendinblue.com/reference#getcontactsfromlist) and 50 per page for [lists](https://developers.sendinblue.com/reference#getlists-1).

[Screenshot](https://i.imgur.com/uAWF1nf.png)

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @alexkorsun 
It will be taken care of in the upcoming release.

Thanks!
