### ISSUE TITLE
What is the API for add transactions on user.

### ISSUE THREAD

**Issue by jihin** [sendinblue/APIv3-nodejs-library#78]
I need to add transactions on user. I cant find any APIs for that. From UI i am able do by editing the user.
![Screenshot 2020-05-06 at 4 06 10 PM](https://user-images.githubusercontent.com/9817635/81174865-9fbb6d80-8fb3-11ea-9ced-aa117b927bc7.png)

**Comment by polesapart** [comment]
And how do I use this data in email templates? Docs have examples about transactional parameters but not about transactional attributes.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @jihin 
I guess you are talking about updating the attributes of a user. Here is an API for it: https://developers.sendinblue.com/reference/updateattribute.


Also, @polesapart the transactional attributes can be used like:
https://developers.sendinblue.com/reference/sendtransacemail, lookout for params field `sendSmtpEmail.params = {"parameter":"My param value","subject":"New Subject"};` in the page.

**Comment by shubhamUpadhyayInBlue** [comment]
This article will also help you: https://help.sendinblue.com/hc/en-us/articles/360000991960
