### ISSUE TITLE
TypeError: SibApiV3Sdk.SMTPApi is not a constructor

### ISSUE THREAD

**Issue by rohanmathewalex** [sendinblue/APIv3-nodejs-library#89]
![errooorr](https://user-images.githubusercontent.com/52772228/101450709-f5dcfe80-3950-11eb-8aba-252f78bc7d6f.JPG)

**Comment by rohanmathewalex** [comment]
![sendinblue email1](https://user-images.githubusercontent.com/52772228/101461942-93402e80-3961-11eb-8d92-4ac751ef01a9.JPG)
![sendinblue-email2](https://user-images.githubusercontent.com/52772228/101461949-9509f200-3961-11eb-88d8-241cb929372e.JPG)

Here in this code i am tryin to do Send a transactional email containing dynamic contact attributes and transactional parameters.
so params i am sending here as  a function
but when i run the code  i am getting atypoe error as shown above.
does anyone know how to solve it?

**Comment by syffs** [comment]
@rohanmathewalex just got that error as well

Take a look at the [doc](https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/TransactionalEmailsApi.md#sendtransacemail)

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @rohanmathewalex

As @syffs has correctly pointed out that the name has been changed in the major release [v8.0.0](https://github.com/sendinblue/APIv3-nodejs-library/releases/tag/v8.0.0). Please refer the [doc](https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/TransactionalEmailsApi.md#sendtransacemail) incase of any doubt.

Thanks!

**Comment by timnqp** [comment]
@syffs Hey thanks!
@shubhamUpadhyayInBlue I was getting the same issue as well by reading [one of your tutorials](https://www.sendinblue.com/blog/send-transactional-emails-with-next-js-and-sendinblue) Maybe someone from SIB can update this tutorial as well?

**Comment by shubhamUpadhyayInBlue** [comment]
Sure @timnqp I will raise the request for it.
