### ISSUE TITLE
Transactional Emails API limit

### ISSUE THREAD

**Issue by HaydenMacDonald** [sendinblue/APIv3-nodejs-library#90]
Hi,

I am getting the following Bad Request error returned from the API when I try to set the `limit` option in `getEmailEventReport(opts)` in `TransactionalEmailsApi`: 

`text: '{"code":"out_of_range","message":"Limit exceeds max value"}'`

The documentation here notes the default value of `limit` is 50, but does not say what the max value is. What is the max value of `limit` for this function?

**Comment by HaydenMacDonald** [comment]
After some testing, I've found that the max value is 100.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @HaydenMacDonald 

You got it right the max value is 100. Sorry, the max value was not mentioned in the [api-doc](https://developers.sendinblue.com/reference). I will forward it as documentation improvement.

Thanks!
