### ISSUE TITLE
some symbols in docs are unreadable

### ISSUE THREAD

**Issue by dyllandry** [sendinblue/APIv3-nodejs-library#93]
So far docs have been a pleasure to read, but on this page <https://github.com/sendinblue/APIv3-nodejs-library/blob/master/docs/CreateContact.md> the description of some properties are encoded funny.

Example:

## Properties
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**email** | **String** | Email address of the user. Mandatory if \&quot;SMS\&quot; field is not passed in \&quot;attributes\&quot; parameter. Mobile Number in \&quot;SMS\&quot; field should be passed with proper country code. For example {\&quot;SMS\&quot;:\&quot;+91xxxxxxxxxx\&quot;} or {\&quot;SMS\&quot;:\&quot;0091xxxxxxxxxx\&quot;} | [optional] 
**attributes** | **Object** | Pass the set of attributes and their values. These attributes must be present in your SendinBlue account. For eg. {\&quot;FNAME\&quot;:\&quot;Elly\&quot;, \&quot;LNAME\&quot;:\&quot;Roger\&quot;} | [optional] 

_(The table continues on the page.)_

**Comment by shubhamUpadhyayInBlue** [comment]
Hello @dyllandry 
Thanks for pointing this out. I have reviewed your PR and will merge and publish it tomorrow. Also, this needs to be fixed in a [few more places](https://github.com/sendinblue/APIv3-nodejs-library/search?p=1&q=%26quot) that I will take care of in our monthly update.
Thanks!
