### ISSUE TITLE
send SMS with sendTransacSms doesn't support emoji 

### ISSUE THREAD

**Issue by damienroche** [sendinblue/APIv3-nodejs-library#97]
Hi here,

We would like to send sms with Emoji,
Unfortunately when we put emoji in our content string, emoji in sms content is replaced by "??"

Does sendinblue api support emoji ?
Thanks

**Comment by shubhamUpadhyayInBlue** [comment]
Hey @damienroche 

In our current `sendTransacSms` API we do not support emojis. However, it would be great if you can share the content that you are trying to send so that we can test it for ourselves. Also, we would try to consider this improvement in our future releases.

Thanks!

**Comment by shubhamUpadhyayInBlue** [comment]
I am closing it since there was no reply in the last 11 days.
