### ISSUE TITLE
Remove contact from automation workflow

### ISSUE THREAD

**Issue by cthomaschase** [sendinblue/APIv3-nodejs-library#98]
Is there an API endpoint to remove a contact from an automation workflow without deleting the contact?

I have an automation that seeds from a contact list. I tried removing the contact from the seed list mid-flow, but that looked to leave the user in the automation flow.

As a fix, I added a condition between each step in the automation that checks if the contact is still in the seed list, if so continue, if no do nothing. This works but seems suboptimal.

Would be nice to be able to remove user from the flow directly through API.

Thanks.

**Comment by shubhamUpadhyayInBlue** [comment]
Hey @cthomaschase 
> to remove a contact from an automation workflow without deleting the contact

We do not have this functionality as of now. But, we have this in the roadmap and it might take some time to implement it.
Thanks!

**Comment by shubhamUpadhyayInBlue** [comment]
Closing this as there is no response for more than 11 days.
